import 'macro-css'
import '../styles/globals.scss'
import {CssBaseline, MuiThemeProvider} from "@material-ui/core";
import {theme} from "../theme";
import Head from "next/head";
import Header from "../components/Header";

function MyApp({Component, pageProps}) {
    return (
        <>
            <Head>
                <title>DelenVk</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link
                    href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,500;0,600;1,300;1,500;1,600&display=swap"
                    rel="stylesheet"/>
            </Head>

            <MuiThemeProvider theme={theme}>
                <CssBaseline/>
              <Header/>
                <Component {...pageProps} />
            </MuiThemeProvider>
        </>
    )
}

export default MyApp
